name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          VERSION=$(npx semver $(npm view semapro@dev version) --increment prerelease --preid dev)
          npm --no-git-tag-version version ${VERSION} && npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
